name: parse_functions
description: Simple functions that can be used to parse values, most often from json.
version: 2.0.1
homepage: https://github.com/KirsApps/parse_functions

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.7.2
  test: ^1.19.4