name: parse_functions
description: Simple functions to help you parse values.
version: 2.0.0
homepage: https://github.com/KirsApps/parse_functions

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: 1.16.8
  pedantic: 1.11.0