name: parse_functions
description: Simple functions to help you parse values.
version: 1.0.0
homepage: https://github.com/KirsApps/parse_functions

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: 1.15.4
  pedantic: ^1.9.2